DELIMITER $$
DROP TRIGGER IF EXISTS TRIG_EMPLOYEE_ONINSERT $$
CREATE TRIGGER `TRIG_EMPLOYEE_ONINSERT` 
AFTER INSERT ON `base_employee`
FOR EACH ROW
BEGIN
    -- CALL PROC_SET_CLAIMPROCESS_FORCALC_1(OLD.`hmo_claim_process_id`);
    -- CALL PROC_CALC_EMPLOYEE_EDUCATION_SUMMARY();

    UPDATE system_summary SET employee_count = (SELECT COUNT(1) FROM base_employee); --  WHERE id=1;
END;
$$
DELIMITER ;